# We need to go back enough to reach a tag
# This was causing issues when functions.cmake
# did git describe --tags --dirty
git:
  depth: 9999999
  
language: cpp
compiler:
  - gcc
  - clang

os: linux
dist: trusty
sudo: required
services: docker

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      compiler: clang
    - os: osx
      osx_image: xcode6.4
      compiler: gcc

branches:
  only:
    - master
    - dev
    
script:
  - "if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then docker run -i -v \"${PWD}:/opt/self\" 32bit/ubuntu:16.04 /bin/bash -c \"linux32 --32bit i386 /opt/self/vm/travis-ci-buildAndTest.sh\" ; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then vm/travis-ci-buildAndTest.sh ; fi"

after_script:
  - build/vm/Self -f objects/worldBuilder.self -o morphic -f2 objects/ci.self
